# Generated by Django 3.0.5 on 2020-04-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200416_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inStock',
            field=models.DecimalField(decimal_places=0, default=100, max_digits=3),
        ),
    ]
