# Generated by Django 3.0.5 on 2020-04-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_instock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='saleToday',
            field=models.BooleanField(default=False),
        ),
    ]
