# Generated by Django 3.0.5 on 2020-04-20 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20200420_1455'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductCategories',
            new_name='ProductCategory',
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
